[project]
name = "kroguname"
version = "0.1.0"
description = "Mix and match first names"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.2.3",
    "parquet[snappy]>=1.3.1",
]
